import React, { Component } from 'react';
import {
    View,
    Button,
    Text,
    Image,
    TouchableOpacity,
    FlatList
} from 'react-native';
import { Dimensions } from 'react-native';

// import stylesheet.
import styles from '../styles';

export default class page2 extends Component {
    render() {
        let style = styles.PageStyle
        let u = Dimensions.get('window').height
        return (
            <View style={style.containerStyle}>
                <Text style={style.titleStyle}>Introduction</Text>
                <Text style={style.contentHead}>One-way trapdoor function</Text>
                <Text style={style.contentStyle}>
                    A trapdoor function is a function that is easy to solve one way but not the other.
                    {"\n"}
                </Text>
                <Image 
                    source={require('./1052px-Trapdoor_permutation.svg.png')}  
                    style={{width: u * 0.1052*3, height: u * 0.0744*3, alignSelf:'center' }}
                />
                
                <Text style={style.contentStyle}>
                    {"\n"}
                    A trapdoor function f with its trapdoor t can be generated by an algorithm Gen.
                    f can be efficiently computed, i.e., in probabilistic polynomial time.
                    However, the computation of the inverse of f is generally hard, unless the trapdoor t is given.
                    {"\n\n"}
                    An example of trapdoor function is the discrete logarithm problem
                    {"\n"}
                    a^k = b
                    {"\n"}
                    Given b, can you find a and k? Probably not in an acceptable amount of time.
                    However you can get b from a^k easily.
                    {"\n\n"}
                    The trapdoor knapsack is a combination of these 2 properties.
                    {"\n"}
                </Text>
            </View>
        )
    }
}
