export default pageThree = {
    "title":"<h1>How does a Trapdoor Knapsack work?</h1>",
    "text": `<p>Trapdoor knapsack is basically formed around 3 different key information, the private key, the multiplier and the modulus. Everything else is derived from these 3 pieces of information.
    The private key is a superincreasing knapsack to ensure there will only be one answer to a ciphertext.
    The modulus chosen is a random integer larger than the sum of elements in the knapsack. This ensures the uniqueness of the ciphertext and plaintext pairs.
    The multiplier chosen is a co-prime to the modulus, so that a multiplicative inverse can be found.
    These three are kept as the secret key by the owner and not distributed.
    
    A public key is generated by multiplying each element of the superincreasing knapsack with the multiplier and modulus to get a difficult knapsack. Since the public key is no longer in a superincreasing sequence, there are multiple solutions to a single ciphertext therefore making it difficult to decipher.
    
    This public key is then given to a person who wishes to send an encrypted text to the owner.
    This person will then encrypts his message using the public key and send it back to the owner.
    The owner with the private key will be able to decrypt and get the original message.
    A detailed example will be given as you progress further.
    
  </p>`
    
  }