export default pageThree = {
    "title":`<h1 style="textAlign: center;">How does a Trapdoor Knapsack work?</h1>`,
    "text": `<p>Trapdoor knapsack is basically formed around 3 different key information, the private key, the multiplier and the modulus<br/><br/>
Everything else is derived from these 3 pieces of information.<br/><br/>
The <b>private key</b> is a superincreasing knapsack to ensure there will only be one answer to a ciphertext.<br/>
The <b>modulus</b> chosen is a random integer <u>larger than the sum of elements in the knapsack</u>. This ensures the uniqueness of the ciphertext and plaintext pairs.<br/>
The <b>multiplier</b> chosen is a <u>co-prime</u> to the modulus, so that a <u>multiplicative inverse</u> can be found.<br/><br/>
These three are kept as the secret key by the owner and not distributed.<br/><br/>
A public key is generated by multiplying <b>each</b> element of the superincreasing knapsack with the multiplier and modulus to get a <b>difficult knapsack</b>.<br/>
Since the public key is no longer in a superincreasing sequence, there are <u>multiple solutions</u> to a single ciphertext therefore making it <u>difficult to decipher</u>.<br/><br/>
This <b>public key</b> is then given to a person who wishes to send an <b>encrypted text</b> to the owner.<br/>
This person will then <b>encrypt</b> his message using the <b>public key</b> and send it back to the owner.<br/>
The owner with the <b>private key</b> will be able to decrypt and get the original message.<br/><br/>
A detailed example will be given as you progress further.
    
  </p>`
    
  }